### ISSUE TITLE
Change the settings screen

### ISSUE THREAD

**Issue by NaomidR** [Kingdorian/Contextproject-BeNine#186]
The sliders in the screen setting should be bigger. 

When editing the settings, it would be usefull to immediately see the changes you made, so that you don't have to save first.

**Comment by jochem725** [comment]
Immediately seeing changes cannot be tested with the settings view, implementing this requires too much effort.

**Comment by bvanwijk** [comment]
I agree with Jochem, the sliders are now bigger #218
