### ISSUE TITLE
Logger displays IndexOutOfBoundsException

### ISSUE THREAD

**Issue by jochem725** [Kingdorian/Contextproject-BeNine#206]
The logger randomly (?) displays an `IndexOutOfBoundsException` which I cannot trace. 
Maybe we can take a look at it.

**Comment by bvanwijk** [comment]
![2016-06-12](https://cloud.githubusercontent.com/assets/9803346/15991343/b31a2d50-30b0-11e6-9804-e4e0d900ef3e.png)

**Comment by Kingdorian** [comment]
I don't know it for sure but I think its when multiple threads (in the http handlers) interact with the logger at the same time. I'll have to take a look at this.

**Comment by Kingdorian** [comment]
Fixed in https://github.com/Kingdorian/Contextproject-BeNine/pull/234
