### ISSUE TITLE
Wrong subview drawing

### ISSUE THREAD

**Issue by jochem725** [Kingdorian/Contextproject-BeNine#240]
The aspect ratio of the subviews drawn on the canvas is incorrect.
It should be close to 16:9 or 5:3, which covers almost the entire stream image.
 
![schermafbeelding 2016-06-15 om 21 41 14](https://cloud.githubusercontent.com/assets/1499711/16094740/eb37eacc-3341-11e6-8027-ec2f89a6c76f.png)

**Comment by Kingdorian** [comment]
Fixed in https://github.com/Kingdorian/Contextproject-BeNine/pull/241
