### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ValMai** [Kingdorian/Contextproject-BeNine#27]
Hi there,

I made a public repository where I will publish feedback every week. Each release on this repository is the feedback for each iteration. 
Here is the first release:
https://github.com/ValMai/cp2016-mm-feedback/releases/tag/iteration1
If you have any questions, don't hesitate to contact me on Slack. 

Regards,
Valentine

**Comment by Kingdorian** [comment]
@ValMai Thank you!

**Comment by jochem725** [comment]
Thanks @ValMai
