### ISSUE TITLE
Communication client - server

### ISSUE THREAD

**Issue by jochem725** [Kingdorian/Contextproject-BeNine#43]
When we created the initial idea, we wanted to let the browser directly communicate with the server.
Since client and server share a different address, the browser poses this as a security threat.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

I propose we change the idea to let NodeJS communicate with the server, since this reduces a high amount of overhead.

**Comment by bvanwijk** [comment]
In #53 this is fixed.
