### ISSUE TITLE
Automatically verify if all dependencies are downloaded before running Node

### ISSUE THREAD

**Issue by jochem725** [Kingdorian/Contextproject-BeNine#55]
Sometimes, new bower dependencies are added requiring `npm install` to be run again. 
This can be done before starting the server in an `npm start` command to make sure all dependencies are always there while running the server.

**Comment by NaomidR** [comment]
This would be very helpful! Also for in the future

**Comment by jochem725** [comment]
I've improved this by moving the bower dependencies to a `bower.json` file.
