### ISSUE TITLE
Database spamming on startup

### ISSUE THREAD

**Issue by jochem725** [Kingdorian/Contextproject-BeNine#89]
The database appears to be spamming the console on startup, it also looks like a new database is created on each start which shouldn't be the case if the database is persistent.

**Comment by bvanwijk** [comment]
![2016-05-13 2](https://cloud.githubusercontent.com/assets/9803346/15258255/d177e706-194a-11e6-85a5-f944763da895.png)

**Comment by bvanwijk** [comment]
fixed in  #92
